defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "package.json" }}
          key: build-{{ .Branch }}
          key: build
      - run: npm ci
      - save_cache:
          key: appTests-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: workspace
          paths:
            - ./*
  appTests:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run:
          name: Run application tests
          command: npm run test:ci | ./node_modules/coveralls/bin/coveralls.js
  integrationTests:
    <<: *defaults
    docker:
      - image: cypress/base:10
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run:
          name: Run integration tests
          command: npm run test:e2e:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - appTests:
          requires:
            - build
      - integrationTests:
          requires:
            - build
