version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
jobs:
  app-tests:
    working_directory: ~/react-universal-app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci --ignore-scripts
      - run:
          name: Run application tests
          command: npm run test:ci | ./node_modules/coveralls/bin/coveralls.js
workflows:
  tests:
    jobs:
      - app-tests
      - cypress/install:
          build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          start: ls -al && pwd && cd integration && npm ci && npm run build && npm run start
          wait-on: 'http://localhost:3000'
