defaults: &defaults
  working_directory: ~/jtart-uni
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "package.json" }}
          key: build-{{ .Branch }}
          key: build
      - run: npm ci
      - save_cache:
          key: build-{{ .Branch }}-{{ checksum "package.json" }}
          key: build-{{ .Branch }}
          key: build
          paths:
            - ~/.npm
            - ~/.cache
            - ~/jtart-uni/node_modules
      - persist_to_workspace:
          root: ~/jtart-uni
          paths:
            - ./*
  app-tests:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/jtart-uni
      - run:
          name: Run application tests
          command: npm run test:ci | ./node_modules/coveralls/bin/coveralls.js
  integration-tests:
    <<: *defaults
    docker:
      - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ~/jtart-uni
      - restore_cache:
          key: integration-{{ .Branch }}-{{ checksum "package.json" }}
          key: integration-{{ .Branch }}
          key: integration
      - run:
          name: Install integration app packages
          command: cd integration && npm ci
      - save_cache:
          key: integration-{{ .Branch }}-{{ checksum "package.json" }}
          key: integration-{{ .Branch }}
          key: integration
          paths:
            - ~/jtart-uni/integration/node_modules
      - run:
          name: Run integration tests
          command: npm run test:e2e
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - app-tests:
          requires:
            - build
      - integration-tests:
          requires:
            - build
