version: 2
jobs:
  appTests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: appTests-{{ .Branch }}-{{ checksum "package.json" }}
          key: appTests-{{ .Branch }}
          key: appTests
      - run: npm ci --ignore-scripts
      - save_cache:
          key: appTests-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run application tests
          command: npm run test:ci | ./node_modules/coveralls/bin/coveralls.js
  integrationTests:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: integrationTests-{{ .Branch }}-{{ checksum "package.json" }}
          key: integrationTests-{{ .Branch }}
          key: integrationTests
      - run: npm install
      - save_cache:
          key: integrationTests-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run integration tests
          command: npm run test:e2e:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - appTests
      - integrationTests
